### ISSUE TITLE
Bug: Error in list of countries for each AS number

### ISSUE THREAD

**Issue by seansaito** [seansaito/YNCTor2MC#1]
In each AS number json object, the country field has duplicate entries (e.g. the same country listed more than once) and also has "Unknown" as an item. Moreover, some AS numbers have more than one country (which shouldn't be the case). For example:

``` javascript
"country": ["gb", "Unknown", "us", "Unknown", "gb", "Unknown", "gb"...
```

**Comment by B0ldy** [comment]
Very strange - the duplicate entries and unknowns are intentional, I was curious to see if there would be differences in country within a single AS number, and it looks like there are. Thoughts Sean?

**Comment by seansaito** [comment]
I guess it is possible then. What are your intentions for including "Unknown" though? Do we need it?

**Comment by B0ldy** [comment]
We don't gain anything by having the "Unknown"s - you're right. I'll put up another iteration without them

**Comment by B0ldy** [comment]
New Commit up - country initials change to full names and "Unknown"s removed
